/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.loginScreens;

import Business.EcoSystem;
import Business.Organization.Organization.Type;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hrishikeshwarrier
 */
public class loginOptions extends javax.swing.JPanel {

    /**
     * Creates new form loginOptions
     */
    JPanel userProcessContainer;
    EcoSystem system;
    Type type;
            
    
    public loginOptions(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdmin = new javax.swing.JButton();
        btnMother = new javax.swing.JButton();
        btnFamily = new javax.swing.JButton();
        btnCounselor = new javax.swing.JButton();
        btnFinance = new javax.swing.JButton();
        btnFinance1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(26, 26, 29));

        btnAdmin.setBackground(new java.awt.Color(252, 68, 69));
        btnAdmin.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(237, 245, 225));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin-with-cogwheels-5.png"))); // NOI18N
        btnAdmin.setText("ADMIN");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnMother.setBackground(new java.awt.Color(252, 68, 69));
        btnMother.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        btnMother.setForeground(new java.awt.Color(237, 245, 225));
        btnMother.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maternity.png"))); // NOI18N
        btnMother.setText("MOTHER");
        btnMother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotherActionPerformed(evt);
            }
        });

        btnFamily.setBackground(new java.awt.Color(252, 68, 69));
        btnFamily.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        btnFamily.setForeground(new java.awt.Color(237, 245, 225));
        btnFamily.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/family.png"))); // NOI18N
        btnFamily.setText("FAMILY");
        btnFamily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamilyActionPerformed(evt);
            }
        });

        btnCounselor.setBackground(new java.awt.Color(252, 68, 69));
        btnCounselor.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        btnCounselor.setForeground(new java.awt.Color(237, 245, 225));
        btnCounselor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/advice.png"))); // NOI18N
        btnCounselor.setText("COUNSELOR");
        btnCounselor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCounselorActionPerformed(evt);
            }
        });

        btnFinance.setBackground(new java.awt.Color(252, 68, 69));
        btnFinance.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        btnFinance.setForeground(new java.awt.Color(237, 245, 225));
        btnFinance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shield-2.png"))); // NOI18N
        btnFinance.setText("INSURANCE");
        btnFinance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceActionPerformed(evt);
            }
        });

        btnFinance1.setBackground(new java.awt.Color(252, 68, 69));
        btnFinance1.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        btnFinance1.setForeground(new java.awt.Color(237, 245, 225));
        btnFinance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-money.png"))); // NOI18N
        btnFinance1.setText("BANK");
        btnFinance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinance1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMother, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCounselor, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinance1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmin)
                    .addComponent(btnFinance))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMother)
                    .addComponent(btnFinance1))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFamily)
                    .addComponent(btnCounselor))
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        loginScreen ls = new loginScreen(userProcessContainer, system, type.HospitalAdmin);
        userProcessContainer.add("loginScreen", ls);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnMotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotherActionPerformed

        loginScreen ls = new loginScreen(userProcessContainer, system, type.BirthMotherOrg);
        userProcessContainer.add("loginScreen", ls);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMotherActionPerformed

    private void btnFamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamilyActionPerformed
        // TODO add your handling code here:
        loginScreen ls = new loginScreen(userProcessContainer, system, type.ParentsOrg);
        userProcessContainer.add("loginScreen", ls);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFamilyActionPerformed

    private void btnCounselorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCounselorActionPerformed
        // TODO add your handling code here:
        loginScreen ls = new loginScreen(userProcessContainer, system, type.Counselor);
        userProcessContainer.add("loginScreen", ls);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCounselorActionPerformed

    private void btnFinanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceActionPerformed
        // TODO add your handling code here:
        loginScreen ls = new loginScreen(userProcessContainer,system, type.InsuranceManager);
        userProcessContainer.add("loginScreen", ls);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFinanceActionPerformed

    private void btnFinance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinance1ActionPerformed
        // TODO add your handling code here:
        loginScreen ls = new loginScreen(userProcessContainer,system, type.BankManager);
        userProcessContainer.add("loginScreen", ls);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFinance1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCounselor;
    private javax.swing.JButton btnFamily;
    private javax.swing.JButton btnFinance;
    private javax.swing.JButton btnFinance1;
    private javax.swing.JButton btnMother;
    // End of variables declaration//GEN-END:variables
}
